app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');


/**
 *
 */
Route::group(['middleware' => 'auth'], function() {

    Route::get('/', function() {
        return view('dashboard');
    });

    Route::get("transactions/json", "TransactionController@getJson");
    Route::resource('transactions', TransactionController::class, [
        'except' => [
            'create', 'edit'
        ]
    ]);


    Route::get('reports', 'ReportController@index');
    Route::get('reports/data', 'ReportController@data');


    Route::resource('categories', CategoryController::class, [
        'except' => [
            'index', 'create', 'show', 'edit'
        ]
    ]);

    Route::group(['middleware' => 'groupAdmin'], function() {
        Route::get('settings/group', 'UserController@getGroupSettings');
        Route::post('settings/group', 'UserController@postGroupSettings');
    });

    Route::get('settings/profile', 'UserController@getSettings');
    Route::post('settings/profile', 'UserController@postSettings');

	Route::get("export", "ExportController@index");
    Route::post('export', 'ExportController@process');

    /**
     * API routes
     */
    Route::group(["prefix" => "api"], function() {
        Route::get('transactions', function(\Illuminate\Contracts\Auth\Guard $auth) {

            $data = $auth->user()->group->transactions()
                ->with('category', 'transaction_type', 'user')
                ->get();

            return [
                'draw' => 1,
                'recordsTotal' => $data->count(),
                'recordsFiltered' => $data->count(),
                'data' => $data
            ];
        });

        Route::get('categories', function() {
            return response()->json( \App\Category::authorized()->get() );
        });
    });
});

app/TransactionType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TransactionType extends Model
{
    //
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use App\User;
use Auth;
use DB;
use Illuminate\Contracts\Auth\Guard;
use Illuminate\Http\Request;

use App\Http\Requests;

class TransactionController extends Controller
{
    /**
     * @param Guard $auth
     * @return \Illuminate\Http\JsonResponse
     */
    public function getJson(Guard $auth)
    {
        return response()->json( $auth->user()->group->transactions );
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Guard $auth)
    {
        return view('transactions.index')
            ->withTransactions( $auth->user()->group->transactions()->with('category', 'transaction_type', 'user')->orderBy('date', 'desc')->get() );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Requests\SaveTransactionRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\SaveTransactionRequest $request)
    {
        return DB::transaction(function() use($request){
            /**
             * @var $transaction Transaction
             */
            $transaction = Auth::user()->transactions()
                ->create($request->except(['_token', '_method']));

            $transaction->calculateRrule( $request );

            return $request->ajax() ?
                response()->json($transaction) :
                redirect()->route('transactions.index');
        });
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Requests\SaveTransactionRequest|Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\SaveTransactionRequest $request, $id)
    {
        return DB::transaction(function() use($request, $id){
            /**
             * @var $transaction Transaction
             */
            $transaction = Auth::user()->transactions()
                ->find($id);


            $transaction->fill($request->all())->save();


            $transaction->calculateRrule( $request );

            return $request->ajax() ?
                response()->json($transaction) :
                redirect()->route('transactions.index');
        });
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }
}

resources/views/transactions/_category_form.blade.php
<form action="{{ empty($category->id) ? route('categories.store') : route('categories.update', $category->id) }}"
      method="{{ empty($category->id) ? 'post' : 'put' }}" class="form" id="category-form" @submit.prevent='saveCategory'>
    {!! csrf_field() !!}
    {!! method_field(empty($category->id) ? 'post' : 'put') !!}

    <div class="form-group" :class="{ 'has-error': errors.name }">
        <label for="name" class="control-label">Name</label>

        <input type="text" id="name" name="name" class="form-control"
               v-model='category.name' placeholder="Category Name" />

        <template v-if="errors.name">
            <span class="help-block">@{{ errors.name }}</span>
        </template>
    </div>

    <button class="btn btn-primary btn-block">Save Category</button>
</form>

@push('scripts')
<script>
    jQuery(function($) {

        var categoryForm = new Vue({
            el: "#category-form",
            parent: bus,

            data: {
                category: {!! $category !!},
                errors: {}
            },

            methods: {
                saveCategory: function() {
                    var $form = $(this.$el),
                        method = $form.attr('method'),
                        action = $form.attr('action');


                    this.$http[method](action, this.category).then(function(response) {
                        //success

                        bus.$broadcast('categories-updated', response.data);
                        bus.$broadcast('update-alerts', {
                            type: 'success',
                            message: 'Successfully Added New Category!'
                        });

                        this.errors = {};
                        this.category = {!! $category !!};

                    }, function(response) {
                        //error

                        this.errors = response.data;
                    });
                }
            }
        });

    });
</script>
@endpush

resources/views/transactions/_form.blade.php
<form action="{{ empty($transaction->id) ? route('transactions.store') : route('transactions.update', $transaction->id) }}"
      method="{{ empty($transaction->id) ? 'post' : 'put' }}" class="form" id="transaction-form" @submit.prevent="onSave">
    {!! csrf_field() !!}
    {!! method_field(empty($transaction->id) ? 'post' : 'put') !!}

    <div class="form-group" :class="{ 'has-error': errors.short_description }">
        <label for="short_description" class="control-label">Short Description</label>

        <input type="text" id="short_description" name="short_description" class="form-control"
               list="shorts" v-model="transaction.short_description" placeholder="Transaction Title" />

        <datalist id="shorts">
            <option v-for="o in short_options" :value="o">@{{ o }}</option>
        </datalist>

        <template v-if="errors.short_description">
            <span class="help-block">@{{ errors.short_description }}</span>
        </template>
    </div>


    <div class="form-group" :class="{ 'has-error': errors.date }">
        <label for="date" class="control-label">Date</label>

        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>

            <input type="datetime" id="date" name="date" class="form-control" v-model="transaction.date">
        </div>

        <template v-if="errors.date">
            <span class="help-block">@{{ errors.date }}</span>
        </template>
    </div>


    <div class="form-group" :class="{ 'has-error': errors.amount }">
        <label for="amount" class="control-label">Amount</label>

        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-dollar"></i></span>

            <input type="text" id="amount" name="amount" class="form-control" v-model="transaction.amount">
        </div>

        <template v-if="errors.amount">
            <span class="help-block">@{{ errors.amount }}</span>
        </template>
    </div>


    <div class="form-group" :class="{ 'has-error': errors.transaction_type_id }">
        <label for="transaction_type_id" class="control-label">Transaction Type</label>

        <select name="transaction_type_id" id="transaction_type_id" class="form-control" v-model="transaction.transaction_type_id">
            <option v-for="tt in transaction_types" :value="tt.id">@{{ tt.type }}</option>
        </select>

        <template v-if="errors.transaction_type_id">
            <span class="help-block">@{{ errors.transaction_type_id }}</span>
        </template>
    </div>


    <div class="form-group" :class="{ 'has-error': errors.category_id }">
        <label for="category_id" class="control-label">Category</label>

        <select name="category_id" id="category_id" class="form-control" v-model="transaction.category_id">
            <option v-for="c in categories" :value="c.id">@{{ c.name }}</option>
        </select>


        <span class="help-block" v-if="errors.category_id">@{{ errors.category_id }}</span>
    </div>

    <button class="btn btn-primary btn-block">Save Transaction</button>
</form>


@push('scripts')
<script>
    jQuery(function($) {
        var url = '{{ url('transactions') }}/{id}';


        var transactionForm = new Vue({
            el: "#transaction-form",
            parent: bus,

            data: {
                transaction: {!! $transaction !!},
                transaction_types: {!! App\TransactionType::all() !!},
                categories: {!! App\Category::authorized()->get() !!},
                short_options: {!! json_encode($short_options) !!},
                errors: {}
            },

            events: {
                'edit': 'onEdit',
                'delete': 'onDelete',
                'categories-updated': function() {
                    this.$http.get('api/categories').then(function(response) {
                        this.categories = response.data;
                    }, function() {

                    });
                }
            },

            methods: {
                "onSave": function() {
                    var $form = $(this.$el),
                            method = $form.attr('method'),
                            action = $form.attr('action');

                    this.$http[method](action, this.transaction).then(function(response) {
                        //success

                        bus.$broadcast('update-transactions');
                        bus.$broadcast('update-alerts', {
                            type: 'success',
                            message: 'Successfully Added New Transaction!'
                        });

                        this.transaction = {!! $transaction !!};
                    }, function(response) {
                        //error

                        this.errors = response.data;
                    });
                },

                "onEdit": function( transaction ) {
                    var $form = $(this.$el);

                    $form.find('[name=_method]').val('put');
                    $form.attr('method', 'put');
                    $form.attr('action', url.replace('{id}', transaction.id));

                    this.transaction = transaction;
                },

                "onDelete": function( id ) {

                }
            }
        });


    });
</script>
@endpush

resources/views/transactions/_repeat_fields.blade.php
<div class="form-group{{ $errors->has('repeats') ? ' has-error' : '' }}">
    <input type="hidden" value="0" name="repeats">

    <label for="repeats" class="control-label">
        <input type="checkbox" value="1" name="repeats" id="repeats" {{ $transaction->repeats ? "checked" : "" }}> Repeats?
    </label>

    @if( $errors->has('repeats') )
        <span class="help-block">{{ $errors->first('repeats') }}</span>
    @endif
</div>

<div class="form-group{{ $errors->has('frequency') ? ' has-error' : '' }}">
    <label for="frequency" class="control-label">Frequency</label>

    <select name="frequency" id="frequency" class="form-control">
        <option value="secondly">By the Second</option>
        <option value="minutely">By the Minute</option>
        <option value="hourly">Hourly</option>
        <option value="daily" {{ empty($transaction->rrule) ? 'selected' : '' }}>Daily</option>
        <option value="weekly">Weekly</option>
        <option value="monthly">Monthly</option>
        <option value="yearly">Yearly</option>
    </select>

    @if( $errors->has('frequency') )
        <span class="help-block">{{ $errors->first('frequency') }}</span>
    @endif
</div>

<div class="form-group{{ $errors->has('interval') ? ' has-error' : '' }}">
    <label for="interval" class="control-label">Interval</label>

    <input type="text" id="interval" name="interval" class="form-control" value="{{ old('interval', 1) }}">

    @if( $errors->has('interval') )
        <span class="help-block">{{ $errors->first('interval') }}</span>
    @endif
</div>


<div>
    <style scoped>
        p .form-control {
            width: auto;
            display: inline;
            padding: 2px;
            text-align: center;
        }

        p input.sm {
            width: 30px;
        }
    </style>

    <p><input type="text" name="count" value="{{ old('interval', 1) }}" class="form-control sm"> times,
        until
        <span class="input-group">
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            <input type="text" name="until" value="{{ old('until', date("Y-m-d H:i:s")) }}" class="form-control">
        </span>,
        <br>every
            <input type="text" name="interval" value="{{ old('interval', 1) }}" class="form-control sm">
        <select name="freq" id="freq" class="form-control">
            <option value="daily">Days</option>
            <option value="weekly">Weeks</option>
            <option value="monthly">Months</option>
        </select>.</p>

    <p><input type="checkbox" name="date"> on
        <select name="byday" class="form-control">
            <option value="su">Sunday</option>
            <option value="mo">Monday</option>
            <option value="tu">Tuesday</option>
            <option value="we">Wednesday</option>
            <option value="th">Thursday</option>
            <option value="fi">Friday</option>
            <option value="sa">Saturday</option>
        </select>
    </p>

    <p><input type="checkbox">
        only when the date is <input type="text" name="bymonthday" class="form-control sm" value="1st">
    </p>
</div>

resources/views/transactions/_table.blade.php
<table class="table table-bordered table-striped table-hover" id="transactions-table" data-order='[[ 2, "desc" ]]' data-page-length='10'>
    <thead>
    <tr>
        <th>User</th>
        <th>Short Description</th>
        <th>Date</th>
        <th>Transaction Type</th>
        <th>Amount</th>
        <th>Category</th>
        <th>Actions</th>
        <th></th>
    </tr>
    </thead>
    <tfoot>
    <tr>
        <th>User</th>
        <th>Short Description</th>
        <th>Date</th>
        <th>Transaction Type</th>
        <th>Amount</th>
        <th>Category</th>
        <th>Actions</th>
        <th></th>
    </tr>
    </tfoot>
</table>

@push('scripts')
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script>
    jQuery(function($){
        var table = $('#transactions-table').DataTable({
            columns: [
                { data: 'user.name' },
                { data: 'short_description' },
                { data: 'date' },
                { data: 'type' },
                {
                    data: 'amount',
                    render: function(amount, method, original, table) {
                        var number = parseFloat(amount);

                        if( original.transaction_type.type == 'expense' ) {
                            number *= -1;
                        }

                        return number.toFixed(2)
                                .replace(/\-/gi, '-$')
                                .replace(/^(\d)/gi, '$$$1');
                    }
                },
                { data: 'category_name' },
                {
                    data: 'id',
                    render: function(id) {
                        return "<span @click='editTransaction("+id+")'><i class='fa fa-edit'></i> Edit</span>";
                    }
                },
                {
                    data: 'id',
                    render: function(id) {
                        return "<span @click='deleteTransaction("+id+")'><i class='fa fa-trash-o'></i> Delete</span>";
                    }
                }
            ],
            ajax: 'api/transactions'
        });


        var vm = new Vue({
            el: '#transactions-table',
            parent: bus,

            data: {
                transactions: {!! $transactions !!}
            },

            methods: {
                editTransaction: function(id) {
                    console.log(id);
                    bus.$broadcast('edit', id);
                },
                deleteTransaction: function(id) {
                    bus.$broadcast('delete', id);
                }
            },

            events: {
                'update-transactions': function() {
                    table.ajax.reload(null, false);
                }
            }
        });

    });
</script>
@endpush

resources/views/transactions/index.blade.php
@extends('layouts.application')

@section('title', 'All Transactions')


@section('breadcrumbs')
    @parent

    <li class="active">
        <i class="fa fa-list-alt"></i> All Transactions
    </li>
@endsection


@push('styles')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">
@endpush


@section('content')
    <div class="row">
        <div class="col-sm-3">

            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">New Transaction</h3>
                </div>
                <div class="panel-body">
                    @include("transactions._form", ['transaction' => new \App\Transaction])
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">New Transaction Category</h3>
                </div>
                <div class="panel-body">
                    @include("transactions._category_form", ['category' => new \App\Category])
                </div>
            </div>
        </div>
        <div class="col-sm-9">

            @include('transactions._table', ['transactions' => $transactions])

        </div>
    </div>
@endsection